services:
  db:
    image: mysql:8.0
    container_name: laptop_db
    restart: always
    environment:
      - MYSQL_DATABASE=wed_compare_laptop_prices
      - MYSQL_ROOT_PASSWORD=giaky113
    volumes:
      - db_data:/var/lib/mysql
      - ./data1.sql:/docker-entrypoint-initdb.d/data1.sql

  php-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    container_name: laptop_scraper_php

volumes:
  db_data: